services:
  server:
    image: nest-api
    build: 
      context: ../server
      dockerfile: ./Dockerfile
      target: development
    ports:
      - "4000:4000"
    volumes: 
      - ../server:/app
      - /app/node_modules
    env_file:
      - ../server/.env
    networks:
      - server_network
    restart: unless-stopped
    command: sh -c 'echo "Running migrations..." && npm run typeorm migration:run -- -d ./src/modules/database/configs/index.ts && echo "Migrations complete." && npm run start:dev'
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    ports:
      - 5433:5432
    networks:
      - server_network
    volumes: 
      - 'postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=weather_app_password

  redis:
    image: redis
    environment:
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
    ports:
      - 6379:6379
    networks:
      - server_network
    restart: unless-stopped
    volumes:
      - redis:/data
    

networks:
  server_network:
    driver: bridge

volumes:
  postgres_data: {}
  redis:
    driver: local