version: '3.8' 

services:
  client:
    build:
      context: ../web
      target: development
      dockerfile: ./Dockerfile
    volumes:
        - ../web:/home/node
        - /home/node/node_modules
        - /home/node/.next
    ports:
      - "3000:3000"

  server:
    build: 
      context: ../server
      dockerfile: ./Dockerfile
      target: development
    ports:
      - "4000:4000"
    volumes: 
      - ../server:/home/node
      - /home/node/node_modules
    env_file:
      - ../server/.env
    networks:
      - server_network
    restart: unless-stopped
    command: sh -c 'echo "Running migrations..." && npm run typeorm migration:run -- -d ./dist/modules/database/configs/index.js && echo "Migrations complete." && npm run start:dev'
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    ports:
      - 5433:5432
    networks:
      - server_network
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes: 
      - 'postgres_data:/var/lib/postgresql/data'

  redis:
    image: redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - 6379:6379
    networks:
      - server_network
    restart: unless-stopped
    volumes:
      - redis:/data
    

networks:
  server_network:
    driver: bridge

volumes:
  postgres_data: {}
  redis:
    driver: local