version: '3.8' 

services:
  server:
    build: 
      context: ../server
      dockerfile: ./Dockerfile
      target: production
    ports:
      - "4000:4000"
    env_file:
      - ../server/.env
    networks:
      - server_network
    restart: unless-stopped
    command: sh -c 'echo "Running migrations..." && npm run typeorm migration:run -- -d ./dist/modules/database/configs/index.js && echo "Migrations complete." && npm run start:prod'
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    ports:
      - 5433:5432
    networks:
      - server_network
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - 6379:6379
    networks:
      - server_network
    restart: unless-stopped

networks:
  server_network:
    driver: bridge
